on: [push]

jobs:
  base: 
    name: "Base"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        name: [michael, timothy]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/reusable.yml