on: [push]

jobs:
  base-1: 
    uses: ./.github/workflows/reusable.yml
    with:
     username: bob-1
  base-2: 
    uses: ./.github/workflows/reusable.yml
    with:
     username: bob-2
  base-3: 
    uses: ./.github/workflows/reusable.yml
    with:
     username: bob-3